#!/usr/bin/env python3
"""pe_manifest.py -- Fingerprint VCDS binaries and generate export manifest for D2XX proxy.

Stage 0 deliverable for PR #4:
Extracts binary metadata, hashes, PE architectures, imports/exports,
ordinal mappings, and generates RTUS64.def for the trace shim.
"""

import hashlib
import json
import os
import sys
from pathlib import Path

try:
    import pefile
except ImportError:
    print("ERROR: pefile not installed. Run: pip install pefile", file=sys.stderr)
    sys.exit(1)

DEFAULT_VCDS_DIR = Path(r"C:\Ross-Tech\VCDS")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while chunk := f.read(65536):
            h.update(chunk)
    return h.hexdigest()


def get_version_info(pe: pefile.PE) -> dict:
    info = {}
    if hasattr(pe, "FileInfo"):
        for fileinfo in pe.FileInfo:
            for item in fileinfo:
                if item.Key.decode("ascii", errors="ignore") == "StringFileInfo":
                    for st in item.StringTable:
                        for entry in st.entries.items():
                            k = entry[0].decode("ascii", errors="ignore")
                            v = entry[1].decode("ascii", errors="ignore")
                            info[k] = v
    return info


def inspect_binary(path: Path) -> dict:
    if not path.exists():
        return {"error": f"File not found: {path}"}

    pe = pefile.PE(str(path), fast_load=False)
    file_sha = sha256_file(path)
    machine_type = "x64" if pe.FILE_HEADER.Machine == 0x8664 else ("x86" if pe.FILE_HEADER.Machine == 0x014C else hex(pe.FILE_HEADER.Machine))

    imports_summary = {}
    if hasattr(pe, "DIRECTORY_ENTRY_IMPORT"):
        for entry in pe.DIRECTORY_ENTRY_IMPORT:
            dll_name = entry.dll.decode("utf-8", errors="ignore")
            funcs = []
            for imp in entry.imports:
                funcs.append({
                    "name": imp.name.decode("utf-8", errors="ignore") if imp.name else None,
                    "ordinal": imp.ordinal
                })
            imports_summary[dll_name] = funcs

    exports_summary = []
    if hasattr(pe, "DIRECTORY_ENTRY_EXPORT"):
        for exp in pe.DIRECTORY_ENTRY_EXPORT.symbols:
            exports_summary.append({
                "ordinal": exp.ordinal,
                "name": exp.name.decode("utf-8", errors="ignore") if exp.name else None
            })

    # Sort exports by ordinal
    exports_summary.sort(key=lambda x: x["ordinal"])

    version_info = get_version_info(pe)

    return {
        "file_name": path.name,
        "path": str(path),
        "size_bytes": path.stat().st_size,
        "sha256": file_sha,
        "machine": machine_type,
        "is_64bit": pe.FILE_HEADER.Machine == 0x8664,
        "num_sections": pe.FILE_HEADER.NumberOfSections,
        "version_info": version_info,
        "imported_dlls": list(imports_summary.keys()),
        "d2xx_imports": [
            {"dll": dll, "functions": imports_summary[dll]}
            for dll in imports_summary
            if any(k in dll.lower() for k in ["rt", "ftd", "usb"])
        ],
        "exports": exports_summary,
        "export_count": len(exports_summary),
    }


def generate_def_file(exports: list, output_path: Path, dll_name: str = "RTUS64", target_orig: str = "RTUS64_orig"):
    """Generate .def file for the proxy DLL."""
    lines = [
        f"; Auto-generated forwarder .def file for {dll_name} D2XX trace shim",
        f"; Generated by pe_manifest.py from genuine Ross-Tech / FTDI binary",
        f"LIBRARY {dll_name}",
        "EXPORTS"
    ]

    for exp in exports:
        name = exp.get("name")
        ord_num = exp.get("ordinal")
        if not name:
            lines.append(f"    {target_orig}.#{ord_num} @{ord_num} NONAME")
        else:
            # We will export function names directly implemented in the proxy or forwarded
            lines.append(f"    {name}={target_orig}.{name} @{ord_num}")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Generated DEF file: {output_path} ({len(exports)} exports)")


def main():
    vcds_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_VCDS_DIR
    out_dir = Path(__file__).parent
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Inspecting VCDS binaries in: {vcds_dir}")
    targets = [
        "RTUS64.dll",
        "RT-USB.dll",
        "VCDS.exeL",
        "VCDSLoader.exe",
        "VCDSScan.exe"
    ]

    manifest = {}
    for t in targets:
        p = vcds_dir / t
        if p.exists():
            print(f"  Analyzing {t}...")
            manifest[t] = inspect_binary(p)
        else:
            print(f"  Skipping {t} (not found)")

    # Save manifest JSON
    manifest_path = out_dir / "pe_manifest.json"
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
    print(f"Saved manifest to: {manifest_path}")

    # Generate RTUS64.def from RTUS64.dll
    if "RTUS64.dll" in manifest and manifest["RTUS64.dll"].get("exports"):
        rtus64_exports = manifest["RTUS64.dll"]["exports"]
        def_path = out_dir / "RTUS64.def"
        generate_def_file(rtus64_exports, def_path, dll_name="RTUS64", target_orig="RTUS64_orig")


if __name__ == "__main__":
    main()
